# Generated by Django 4.2.21 on 2025-05-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordclass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedclass',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
