# Generated by Django 4.2.21 on 2025-05-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('tutor_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('course_name', models.CharField(max_length=255)),
                ('online_class_link', models.URLField()),
            ],
        ),
    ]
