# Generated by Django 4.2.21 on 2025-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineclass',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
