# Generated by Django 4.2.21 on 2025-05-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0002_alter_onlineclass_date_alter_onlineclass_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineclass',
            name='thumbnail',
            field=models.ImageField(upload_to='online_thumbnails/'),
        ),
    ]
